apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgagent-cronjob
spec:
  # Runs every minute. You can adjust this schedule.
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pgagent
              image: crunchydata/crunchy-pgagent:latest
              env:
                - name: PGAGENT_DB_HOST
                  value: "postgres-service"
                - name: PGAGENT_DB_PORT
                  value: "5432"
                - name: PGAGENT_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: PGAGENT_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGROW_PASSWORD
                - name: PGAGENT_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_DB
          restartPolicy: OnFailure