apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing-job
spec:
  template:
    spec:
      containers:
        - name: data-processing
          image: data_processing
      restartPolicy: Never
