apiVersion: v1
kind: ConfigMap
metadata:
  name: renderd-config
data:
  renderd.conf: |
    [renderd]
    num_threads=4
    tile_dir=/var/lib/mod_tile
    stats_file=/var/run/renderd/renderd.stats
    font_dir_recurse=1

    [mapnik]
    plugins_dir=/usr/lib/x86_64-linux-gnu/mapnik/4.0/input/
    font_dir=/usr/share/fonts/
    font_dir_recurse=1

    [default]
    URI=/hot/
    XML=/usr/local/share/maps/style/openstreetmap-carto/mapnik.xml
    HOST=localhost
    TILESIZE=256
  mapnik-style.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE Map[]>
    <Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs" background-color="#f2efe9">
    </Map>