apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-deployment
  labels:
    app: osrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrm
  template:
    metadata:
      labels:
        app: osrm
    spec:
      containers:
        - name: osrm
          image: osrm
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: osrm-service
spec:
  selector:
    app: osrm
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
