# ui/tui_logging.py
# -*- coding: utf-8 -*-
"""
Logging handler for the TUI.
"""

import logging
import threading

import urwid  # type: ignore[import-untyped]

# Assuming tui_widgets.py is in the same directory (ui/)
from .tui_widgets import LogDisplay


class TuiLogHandler(logging.Handler):
    """
    Custom logging handler for integrating Python logging with a TUI (Text-based User Interface)
    log display.

    The TuiLogHandler class routes log messages generated by the Python `logging` library to
    a log display widget in a Text-based User Interface (TUI) powered by the `urwid` library.
    It facilitates real-time logging display and supports multi-threaded environments by ensuring
    that updates to Urwid widgets are properly synchronized via the main event loop.

    Attributes:
        log_display_widget (LogDisplay): The widget used for displaying log messages in the TUI.
        main_loop (urwid.MainLoop): The main event loop for the Urwid-based TUI application.
        formatter (logging.Formatter): Formatter instance specifying how log records are formatted.
    """

    def __init__(
        self, log_display_widget: LogDisplay, main_loop: urwid.MainLoop
    ):
        super().__init__()
        self.log_display_widget = log_display_widget
        self.main_loop: urwid.MainLoop = main_loop
        self.formatter = logging.Formatter(
            "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            datefmt="%H:%M:%S",
        )

    def emit(self, record: logging.LogRecord) -> None:
        try:
            msg = self.format(record)
            level_name = record.levelname.lower()
            if threading.current_thread() is threading.main_thread():
                self.log_display_widget.add_message(msg, level=level_name)
            else:  # pragma: no cover

                def _update_log_display_from_thread():
                    self.log_display_widget.add_message(msg, level=level_name)

                self.main_loop.alarm(
                    0,
                    lambda _loop_unused,
                    _data_unused: _update_log_display_from_thread(),
                )  # type: ignore[attr-defined]
        except RecursionError:  # pragma: no cover
            raise
        except Exception:  # pragma: no cover
            self.handleError(record)
