# Use the official Certbot image
FROM certbot/certbot:latest

# The entrypoint is 'certbot'.
# Arguments will be provided in the Kubernetes manifest to obtain or renew certificates.
ENTRYPOINT [ "certbot" ]
