apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  init-postgis.sh: |
    #!/bin/sh
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE EXTENSION IF NOT EXISTS postgis;
        CREATE EXTENSION IF NOT EXISTS postgis_topology;
        CREATE EXTENSION IF NOT EXISTS hstore;
        -- Grant schema privileges
        GRANT CREATE, USAGE ON SCHEMA public TO "$POSTGRES_USER";
        -- Grant privileges on existing objects created by extensions
        GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO "$POSTGRES_USER";
        GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "$POSTGRES_USER";
        GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO "$POSTGRES_USER";
        -- Grant default privileges for future objects created by the user
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO "$POSTGRES_USER";
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "$POSTGRES_USER";
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO "$POSTGRES_USER";
    EOSQL
  postgresql.conf: |
    # --- TRANSIT SERVER CUSTOMISATIONS ---
    listen_addresses = '*'
    shared_buffers = 2GB
    work_mem = 256MB
    maintenance_work_mem = 2GB
    checkpoint_timeout = 15min
    max_wal_size = 4GB
    min_wal_size = 2GB
    checkpoint_completion_target = 0.9
    effective_cache_size = 6GB
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_min_duration_statement = 250ms
    # --- END TRANSIT SERVER CUSTOMISATIONS ---
  pg_hba.conf: |
    # pg_hba.conf
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             postgres                                peer
    local   all             all                                     peer
    local   gis             osmuser                                 scram-sha-256
    host    all             all             127.0.0.1/32            scram-sha-256
    host    gis             osmuser         127.0.0.1/32            scram-sha-256
    host    gis             osmuser         192.168.128.0/22        scram-sha-256
    host    all             all             ::1/128                 scram-sha-256
    host    gis             osmuser         ::1/128                 scram-sha-256