# ojp-server/kubernetes/components/postgres/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - secret.yaml
  - configmap.yaml
  - network-policy.yaml