apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # IMPORTANT: Change this for production
  POSTGRES_USER: "osmuser"
  POSTGRES_PASSWORD: "yourStrongPasswordHere"
  POSTGRES_DB: "gis"
  DATABASE_URL: "postgresql://osmuser:yourStrongPasswordHere@postgres-service:5432/gis"