apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # These values should be changed for production
  POSTGRES_USER: "gis"
  POSTGRES_PASSWORD: "gis"
  POSTGRES_DB: "gis"
  DATABASE_URL: "postgresql://gis:gis@postgres-service:5432/gis"
