apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: OpenJourneyServer

resources:
- namespace.yaml
- ../components/postgres
- ../components/nginx
- ../components/nodejs
- ../components/certbot
- ../components/self-signed-certs

# Common labels to apply to all resources
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: oj-server
