apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: OpenJourneyServer

resources:
- namespace.yaml
- ../components/postgres
- ../components/osrm
- ../components/pg_tileserv
- ../../plugins/Public/OpenStreetMap/kubernetes
- ../components/apache
- ../components/nginx
- ../components/nodejs
- ../components/certbot
- ../components/pgadmin
- ../components/pgagent
- ../components/data_processing
- ../components/py3gtfskit

# Common labels to apply to all resources
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: oj-server
