# Use the official pgAdmin 4 image
FROM dpage/pgadmin4:latest

# Environment variables for configuration will be provided via a ConfigMap or Secret.
# For example:
# ENV PGADMIN_DEFAULT_EMAIL=admin@example.com
# ENV PGADMIN_DEFAULT_PASSWORD=admin

EXPOSE 80
