apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/nginx
  - ../../components/self-signed-certs
patches:
  - path: nginx-config-patch.yaml
    target:
      kind: ConfigMap
      name: nginx-config