apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

namePrefix: prod-

# Patch image paths to point to the production private registry (e.g., Harbor)
images:
  - name: postgres
    newName: harbor.your-domain.com/ojp/postgres
  - name: osrm
    newName: harbor.your-domain.com/ojp/osrm
  - name: pg_tileserv
    newName: harbor.your-domain.com/ojp/pg_tileserv
  - name: renderd
    newName: harbor.your-domain.com/ojp/renderd
  - name: apache
    newName: harbor.your-domain.com/ojp/apache
  - name: nginx
    newName: harbor.your-domain.com/ojp/nginx
  - name: carto
    newName: harbor.your-domain.com/ojp/carto
  - name: nodejs
    newName: harbor.your-domain.com/ojp/nodejs
  - name: certbot
    newName: harbor.your-domain.com/ojp/certbot
  - name: pgadmin
    newName: harbor.your-domain.com/ojp/pgadmin
  - name: pgagent
    newName: harbor.your-domain.com/ojp/pgagent
  - name: data_processing
    newName: harbor.your-domain.com/ojp/data_processing
  - name: py3gtfskit
    newName: harbor.your-domain.com/ojp/py3gtfskit

# Patch deployments for higher availability
patches:
  - target:
      kind: Deployment
      name: osrm-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
