apiVersion: batch/v1
kind: Job
metadata:
  name: carto-style-copier
spec:
  template:
    spec:
      containers:
        - name: carto-styler
          image: carto
          command: ["cp", "-r", "/src/styles/.", "/mnt/styles"]
          volumeMounts:
            - name: carto-styles
              mountPath: /mnt/styles
      volumes:
        - name: carto-styles
          persistentVolumeClaim:
            claimName: carto-style-pvc
      restartPolicy: Never
  backoffLimit: 4