apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: promtail
  labels:
    app: promtail
    component: logging

resources:
- daemonset.yaml
- service.yaml
- configmap.yaml

commonLabels:
  app: promtail
  component: logging

namespace: default