apiVersion: v1
kind: Service
metadata:
  name: promtail
  labels:
    app: promtail
    component: logging
spec:
  type: ClusterIP
  ports:
  - port: 3101
    targetPort: 3101
    protocol: TCP
    name: http-metrics
  selector:
    app: promtail