apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
    component: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
        component: logging
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        ports:
        - containerPort: 3100
          name: http
        args:
        - -config.file=/etc/loki/local-config.yaml
        - -target=all
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki
        env:
        - name: JAEGER_AGENT_HOST
          value: ""
        - name: JAEGER_ENDPOINT
          value: ""
        - name: JAEGER_SAMPLER_TYPE
          value: ""
        - name: JAEGER_SAMPLER_PARAM
          value: ""
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        persistentVolumeClaim:
          claimName: loki-pvc
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001