apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: loki
  labels:
    app: loki
    component: logging

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- pvc.yaml

commonLabels:
  app: loki
  component: logging

namespace: default