apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  labels:
    app: loki
    component: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""